site_name: Cheat Sheets
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: purple

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  # - pymdownx.inlinehilite
  # - pymdownx.snippets
  # - admonition
  # - pymdownx.arithmatex:
  #     generic: true
  - pymdownx.superfences